Initial Untracked Transactions Viewing & Updating
eliotmjohnson/BudgetBros pull request #130
Opened 2024-12-09 03:56 UTC by johnsonav1992

2024-12-09 14:26 UTC, eliotmjohnson requested changes

2024-12-09 14:26 UTC, eliotmjohnson commented on src/app/services/transaction.service.ts
> +    newlyCreatedTransactionId = signal<string | null>(null);
Could you revert this back to a Subject? I had a specific implementation with it and I don't want to use signals here.

2024-12-09 14:26 UTC, eliotmjohnson commented on src/app/services/line-item.service.ts
>              !this.fetchedLineItem ||
This should be invoked as well

2024-12-09 14:26 UTC, eliotmjohnson commented on src/app/components/transaction-modal/transaction-modal.component.ts
> +            newTransaction.lineItemId &&
Could you revert this back to a Subject? I had a specific implementation with it and I don't want to use signals here.

2024-12-09 14:26 UTC, eliotmjohnson commented on src/app/services/transaction.service.ts
> +                        this.newlyCreatedTransactionId.set(
Here as well

2024-12-09 15:15 UTC, johnsonav1992 commented on src/app/components/transaction-modal/transaction-modal.component.ts
> +            newTransaction.lineItemId &&
Oh sorry! Haha I did this to test something and then forgot about it. Whoops!

2024-12-12 03:37 UTC, eliotmjohnson approved these changes

2024-12-12 03:37 UTC, merged